class Panel {
    constructor() {
      this.palabras = ;
      this.palabraElegida2 = "";
      this.vectorAdivinanza2 = [];
      this.vectorRespuesta2 = [];
      this.intentos = 7;
  
    }
    prueba(nombrePokemon){
      console.log(nombrePokemon);
    }

  //   dibujarLineasModificar() {
  //     let idpalabra = 0;
      
  //     idpalabra = Math.floor(Math.random() * 200);
      
  //     this.palabraElejida2 = this.palabras[idpalabra];
  
  //     console.log(this.palabraElejida);
      
  //     this.vectorRespuesta2 = Array.from(this.palabraElejida);
      
  //     for (let index = 0; index < this.palabraElejida2.length; index++) {
  //       this.vectorAdivinanza2.push("_");
  //     }
  //     return this.vectorAdivinanza2;
  //   }
  // }

  //   if (verifica) {
  //     button.classList = "blue";
  //   } 
    
  //   const verifica = Panels.showCorrect2(e.target.textContent, conta);
